### ISSUE TITLE
Benchmark graphs not displaying for "Energy efficiency contractors"

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#101]
Check if this is a general issue or limited to Energy efficiency contracting segment.

**Comment by deborabonner** [comment]
Addressed by re-opening # 92

**Comment by smirolo** [comment]
Sections were not marked to be displayed as graph.
![screen shot 2017-08-14 at 11 06 18 am](https://user-images.githubusercontent.com/3732869/29285145-589116d6-80e2-11e7-91aa-e8fa8bf3b14b.png)

fixed by adding sections to be displayed as graphs.
