### ISSUE TITLE
Improvement planning dashboard major malfunctions

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#102]
Looks like the issue is that the "Improvement planning" page is displaying an older version of the content than "Environmental practices"or "Self assessment" pages.  So, if one un/checks an item from the "Select for improvement plan" column that is no longer aligned with the new content, one gets a pink "Error: Not found."
The Improvement planning dashboard also then became totally insensible, plus and I couldn't close it. Had to close the browser to escape the page. 

![capture2](https://user-images.githubusercontent.com/26979575/29252784-87151338-8022-11e7-9a40-2620d3622156.PNG)

![capture](https://user-images.githubusercontent.com/26979575/29252779-79c253ee-8022-11e7-8453-a5aad3a22cfb.PNG)

**Comment by deborabonner** [comment]
Distortions as seen on this url need correcting:

https://tspproject.org/app/erin-org/improve/sustainability-epc/

**Comment by smirolo** [comment]
Related to #47 "Engineering, Procurement, Construction" is a much longer title than all others.
