### ISSUE TITLE
Benchmark graph headings: First heading should be top icon NOT industry segment

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#108]
Apologies not noticing this earlier. or is it a new thing?  I elevated it to a "b4" label, because it looks like an error to have for example "Engineering, procurement, construction" repeat across every benchmark graph. Plus without the first heading being the top level icon, the graphs don't have context.

See the benchmark graphs at this url for example:
https://tspproject.org/app/erin-org/benchmark/sustainability-epc/

**Comment by smirolo** [comment]
Commits related to #40 use the breadcrumbs for benchmark titles. This is only correct for headings lifted up as benchmark.
