### ISSUE TITLE
Average value column: If the average value is 2.5 or greater, it should round up to 3. 

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#116]

**Comment by deborabonner** [comment]
What I discovered this weekend: If I have 3 dark green cells and one medium, with an Average value cell that is medium green, if I change one of the cells values and then change is back again to what I want, the Average value cell changed to dark green.  I can webex demo it for you if that explanation isn’t clear.

**Comment by smirolo** [comment]
done. re-run the migrate_production command with `recompute_avg_value()` enabled.
