### ISSUE TITLE
Use template spreadsheet for "Improvement Plan"

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#125]
Deb to provide format

**Comment by deborabonner** [comment]
Download improvement plan leads to download into a pre-formatted xls table with pre-existing headings.  Table includes download of bps values

**Comment by smirolo** [comment]
Possible included in #167 feature requirements.

**Comment by deborabonner** [comment]
Closing this issue, because I agree with smirolo statement above -  its covered by #167 and also #122
