### ISSUE TITLE
MyTSP optimization

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#131]
can wait for first subscriber

**Comment by smirolo** [comment]
Time to present graphs much improved but overall both Reporting Entities and Performance Graphs page still take 16 to 18 seconds to present

**Comment by smirolo** [comment]
Closing. Performance is not a blocker anymore (at least for now).

**Comment by deborabonner** [comment]
Processing very slow again.

**Comment by smirolo** [comment]
Previous commit gets performance back into interactive range.
