### ISSUE TITLE
MyTSP: Ensure all drill down graphs are showing up

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#132]

**Comment by smirolo** [comment]
Closing. I went through the database to add survey_matrix and survey_editablefilter for all industry segment and added missing ones.

**Comment by deborabonner** [comment]
Total scores by industry segment: Clicking "Construction: results in error 404 page
Portfolio topic drill downs: can drill down to scorecards from these graphs

**Comment by smirolo** [comment]
The issue stems from industry segments that were entered manually as a workaround missing #53 feature.

**Comment by smirolo** [comment]
The topic drill-down are added automatically based on the results of the API call (commit e2a0e357). Thus only needs to check the top-level industry segments have an associated `Matrix`.
