### ISSUE TITLE
Opportunity score: normalize to percentage points

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#145]

**Comment by smirolo** [comment]
Implemented in the context where *all* icon weights is 1.0. Still have to see if it is feasible with random weights. Possible the requirements is drop as per-conversation.

**Comment by smirolo** [comment]
The "Opportunity Score" columns shows the number of points (computing change in total score percentage in the context of #159 is an open question). 

Last commit prints "N/A" instead of zero for practices which have been answered "N/A". This is last
