### ISSUE TITLE
IE: Make font size and style match version which shows in Chrome

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#146]
On Homepage:

![capture](https://user-images.githubusercontent.com/26979575/31024503-1fb2ebe2-a4f4-11e7-921b-aef13aa9e0c1.PNG)

**Comment by smirolo** [comment]
It is most likely an issue between fonts installed on Windows and MacOS rather than a IE/Chrome difference. Some text might defaults to use native fonts instead of the webfont specified in the HTML head.

**Comment by smirolo** [comment]
Tried with IE11 and the correct web font (Myriad light) is used.

**Comment by smirolo** [comment]
Looks like it is resolved on all versions of IE.
