### ISSUE TITLE
Add/remove organization on MyTSP

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#155]
Only the Manager of the MyTSP org can add or remove suppliers from the reporting entity list.
Contributor can see the list and see the scorecards

**Comment by smirolo** [comment]
Closely related to #161 and #164

**Comment by smirolo** [comment]
Remains: text of the two e-mails:

1. send to supplier when a utility adds the Organization to the dashboard (request)
2. send to utility when supplier approved request (complete double opt-in)

**Comment by deborabonner** [comment]
1. In MyTSP, change text in the orange button from "Request access" to "Add reporting entity"
2. MyTSP: Create emails for adding reporting entities and sharing scorecards (see attached Word doc).
[Email templates.docx](https://github.com/djaodjin/envconnect/files/1717876/Email.templates.docx)

**Comment by smirolo** [comment]
remain items split in their own issues.
