### ISSUE TITLE
Scorecard (on screen and pdf): List "NA" responses

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#157]
Scorecard modifications: see blue edits in attached, plus new third page.

[tsp-scorecard layout.pdf](https://github.com/djaodjin/envconnect/files/1608220/tsp-scorecard.layout.pdf)

Added previously in #138:
- Title: Include reporting entity name after "Scorecard - "
- Font of the total score match the website and the rest of the print out.
- Benchmark graphs: 
1) Center both columns of benchmark graphs (i.e. away from the left hand side of the page  by a centimeter,  increase the margin between the two graphs).
2) Match icon graphics to versions presented in "scorecard" at top of page (at moment, words appear in the graphics which are too large and out of alignment)
2) Shrink and/or wrap heading text

**Comment by smirolo** [comment]
Incorrect issue was referenced. It should have been #168

**Comment by deborabonner** [comment]
Any reference to improvement actions or plans was deleted from the above with the rationale that we should keep the Scorecard separate from the Improvement Plan.

**Comment by smirolo** [comment]
1. `not_applicable_answers` is not loading and displaying the correct data.
2. Remains to add N/A answers to the PDF.

**Comment by deborabonner** [comment]
o	Need to print the bp heading with the bps, if there is one

**Comment by smirolo** [comment]
Split remaining items into their own issues.
