### ISSUE TITLE
Score on each icon to be normalized

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#159]
Score to be calculated based on icon weights, not number of best practices.

**Comment by smirolo** [comment]
related to update to formulas to compute scores as is #154

**Comment by smirolo** [comment]
Check how this feature and previous commits affect current scores. (#139)

**Comment by smirolo** [comment]
The function `print_account_updated_scores` in migrate_production.py was used to compare before and after scores. Only 3 accounts have changes of more than 10% in some of their icon scores.

Feature is enabled as part of previous commit.
