### ISSUE TITLE
Planning dashboard – modify (see mock up below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#168]
[tsp-planning dashboard.pdf](https://github.com/djaodjin/envconnect/files/1604237/tsp-planning.dashboard.pdf)

**Comment by deborabonner** [comment]
Attached is a mock up that shows and describes planning dashboard changes. Mock ups for buttons "Improvement plan" and "Scorecard after improvement" underway.   
[tsp-planning dashboard.pdf](https://github.com/djaodjin/envconnect/files/1601512/tsp-planning.dashboard.pdf)

**Comment by smirolo** [comment]
Split remaining items into their own issue.
