### ISSUE TITLE
Support assessment over multiple periods

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#172]
By way of #162 and #170, the process requires to calculate and display scores over multiple periods (year 2017, 2018, etc.)

**Comment by deborabonner** [comment]
MOCK UP FOR HOW GRAPHS SHOULD BE DESIGNED

[How to present scoring over time (2).pdf](https://github.com/djaodjin/envconnect/files/1641215/How.to.present.scoring.over.time.2.pdf)

**Comment by smirolo** [comment]
The previous commit implements mockup of historical data only.

**Comment by smirolo** [comment]
API and database-side completed. Please open new issues if updates are required on the chart layout.
