### ISSUE TITLE
Assessment & Planning > "Implementation rate": Increase text contrast where "0%"

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#179]
Proposal: Either change the background color to a darker grey, or make the text grey when response rate is "0%". 

![capture](https://user-images.githubusercontent.com/26979575/34234063-b309108a-e59d-11e7-8c6e-adae03a0e068.PNG)

**Comment by smirolo** [comment]
The 0% is aligned to the left because the text is "centered" on the green bar (which is of width == 0 then).
