### ISSUE TITLE
Text additions & modifications (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#184]
These are intended to take the guesswork out of the site functions and work flow for a first time user. 
[tsp text additions4.pdf](https://github.com/djaodjin/envconnect/files/1857661/tsp.text.additions4.pdf)

**Comment by smirolo** [comment]
Page 1 was implemented.

**Comment by deborabonner** [comment]
The attached shows the remaining text modifications that need to be made: 
[tsp text additions.pdf](https://github.com/djaodjin/envconnect/files/1813218/tsp.text.additions.pdf)

**Comment by smirolo** [comment]
Last commit should implement the remaining text updates and onboarding pop-ups.

**Comment by smirolo** [comment]
The last page (i.e. page 8) describes the dialog box that appears when a user clicks the "Complete" button on their improvement planning. It is not meant to show up the first time a user clicks on the Planning link.
Are we looking at the same document? Is there a page missing?
