### ISSUE TITLE
Value definitions (color key): Make more "psychologically accessible" (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#185]
A user clicks on the color "Legend" or "Key" and they're taken one of the three value definitions documents attached below. Which value def document they're taken to depends on the "industry segment" they selected when registering their organization on TSP. 

**Value definitions - 1:** Consulting/Advisory services, Professional services
**Value definitions - 2:** Architects, Construction, Distribution/Logistic & shipping, General contracting, Engineering, Eng procurement construction, Enviro consulting engineering construction, Facilities management, Interior design, Lab services, Rental equipment & parts, Value added reselling, Vegetation management
**Value definitions - 3:** Energy efficiency contracting, Energy utility (supply chain), Fuel supply, Freight/shipping, Marketing & comm, Print services, Waste management

[Value definitions - 1.docx](https://github.com/djaodjin/envconnect/files/1636297/Value.definitions.-.1.docx)
[Value definitions - 2.docx](https://github.com/djaodjin/envconnect/files/1636298/Value.definitions.-.2.docx)
[Value definitions - 3.docx](https://github.com/djaodjin/envconnect/files/1636299/Value.definitions.-.3.docx)

**Comment by deborabonner** [comment]
Associate the legends as follows for the below list of industry segments: 
- Materials planning & recovery (Value def 3)
- General manufacturing (nothing for now)
- Electric procurement, (Value def 3)
- Gas procurement, (Value def 3)
- Corporate/ shared services, (Value def 3)
- Boxes & enclosures, (Nothing for now)
- Wire & cable (nothing for now)
- Fabricated metals (nothing for now)
- Distribution transformers (nothing for now)

**Comment by smirolo** [comment]
All updates were applied to the database.

**Comment by smirolo** [comment]
Add expand behavior on +/- buttons.
