### ISSUE TITLE
MyTSP: Performance graphs, Portfolio topic drill down - error (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#201]
Clicking on any bar in the Portfolio topic drill down, I get to click through to a scorecard, but a pink menu bar appears atop the page that reads “Error: permission denied”

**Comment by smirolo** [comment]
1. Added access rule for contributor:

    UPDATE rules_rule SET kwargs ='{"organization": "", "roledescription": ["viewer", "contributor"]}' WHERE path='/api/:organization/benchmark/'; 

2. Make sure staging and production use different db names even on different hosts.

Please re-open if the issue still appears.
