### ISSUE TITLE
Dashboard: Minor edits (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#227]

**Comment by deborabonner** [comment]
Bold the text "# Reporting organizations"
Plus uncapitalize the "R"

**Comment by deborabonner** [comment]
-- 9 Reporting organizations: Change R to lower case.

-- Search function: create a bit of space between the top and bottom of the search box.
<img width="1311" alt="screen shot 2018-09-26 at 10 47 17" src="https://user-images.githubusercontent.com/26979575/46072302-ed39ec80-c179-11e8-9d36-28f853cd4ade.png">

**Comment by smirolo** [comment]
Change the search functionality to not trigger automatically as typing but after clicking on a "search button".
