### ISSUE TITLE
Dashboard (EUISSCA): For Members & Administrators (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#230]
**•	Dashboard accessible exclusively by EUISSCA third party Administrators**
 [See mock up for specifications]
[Github 230 (EUISSCA admin dashboard).pdf](https://github.com/djaodjin/envconnect/files/2406029/Github.230.EUISSCA.admin.dashboard.pdf)

**•	Dashboard for EUISSCA members that includes (Part 1):**  
[See mock up for specifications].
[230 - Dashboard for members.pdf](https://github.com/djaodjin/envconnect/files/2411005/230.-.Dashboard.for.members.pdf)

**Comment by deborabonner** [comment]
I am deleted the below from the list of to-do's for this issue, because we ended up going a different route. We are using 2018 to gather information on what metrics suppliers are reporting externally. Based on that data, we will determine if required or requesting that suppliers report to pre-set metrics (e.g. GHG emissions) makes sense. 

**•	Dashboard for EUISSCA members that includes (Part 2):**  
5)	Ability to view results per Supplier for environmental impacts (ex. GHG emissions, energy, water, waste, compliance,) totaled per impact per year with comparison year over year. [This relates to data entry fields i.e. volumes waste generated, GHG emissions, etc]. (DB MOCK UP - This is a dashboard view we agreed we could push out until later].

**Comment by smirolo** [comment]
This functionality was implemented (differently) as part of the "supplier full chain" feature.
