### ISSUE TITLE
Home page: design modification 

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#231]
The attached mock up was reviewed and approved by the EUISSCA KSP team. It includes a EUISSCA-branded home page with navigation pathways into TSP that align with the key user use cases. 
[EUISSCA Home Page & navigation paths.pdf](https://github.com/djaodjin/envconnect/files/2146156/EUISSCA.Home.Page.navigation.paths.pdf)

**Comment by smirolo** [comment]
Page 2:
"EUISSCA Sustainability Framework Take/update maturity assessment" doesn't lead anywhere at the moment?

Page 7:
"c. See guidance on the above choices:" doesn't lead anywhere at the moment?

Page 10:
_"Click on Dashboard."_ - Does it mean we rename "MyTSP" menu into "Dashboard"?
TODO: _[insert draft email text]_

**Comment by deborabonner** [comment]
See attached for modifications related to your above queries. 
Yes, I propose we change "MyTSP" to "Dashboards".

[EUISSCA Home Page & navigation paths (v2).pdf](https://github.com/djaodjin/envconnect/files/2156665/EUISSCA.Home.Page.navigation.paths.v2.pdf)

**Comment by smirolo** [comment]
All done except shrinking icons. The text inside the icons is too long with a wide variety of full length. It wraps around making the squares rectangles, as well as of different length.
My suggestion would be to move the text out of the icons and use icons of same size as on industry segment pages (i.e. something looking like the headers about the charts on the scorecard). That will help with various screen widths as well as make the overall look more consistent.

**Comment by deborabonner** [comment]
- Make the green text "Powered by the Sustainsbility Project" darker or white. 
- Instead of tiles, use orange button with drop down as shown in original pdf

**Comment by smirolo** [comment]
made the look of the page consistent with FAQs/Tutorials
