### ISSUE TITLE
Scorecard pdf downloads: Give label that includes "supplier x scorecard and date"

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#241]

**Comment by smirolo** [comment]
Is the current design not fulfilling the requirements?
![screen shot 2018-06-27 at 1 52 32 am](https://user-images.githubusercontent.com/3732869/41963713-1c51c124-79ad-11e8-9aa5-ce3c48023075.png)

**Comment by deborabonner** [comment]
Yes it does. I must have forgotten to close the issue.
