### ISSUE TITLE
Complete "data entry" capability/feature 

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#242]
System for inputting, tracking, and trending environmental impacts (ex. GHG emissions, energy, water, waste, compliance,) per reporting entity and in total impact per year with comparison year over year. (DB MOCK UP)

**Comment by deborabonner** [comment]
Mock up.
[#242.pdf](https://github.com/djaodjin/envconnect/files/2168520/242.pdf)

**Comment by smirolo** [comment]
Fully implements the mockups. Measures can be inputed through 2 kinds of input screen and db was updated.
Missing: display of results on the scorecard.

**Comment by deborabonner** [comment]
Noted! Will send mock up by day's end. D. 

    On Monday, August 27, 2018 10:31 AM, Sebastien Mirolo <notifications@github.com> wrote:
 

 Fully implements the mockups. Measures can be inputed through 2 kinds of input screen and db was updated.
Missing: display of results on the scorecard.—

**Comment by deborabonner** [comment]
I did provide the "display of results on scorecard". See pdf above titled "242_scorecard presentation". Or is this not adequate.

**Comment by smirolo** [comment]
Results showing on assessment spreadsheet, scorecard and scorecard PDF.

**Comment by deborabonner** [comment]
Best practice that needs changing, that I've not been able to edit.

[Change to a bp.pdf](https://github.com/djaodjin/envconnect/files/2402371/Change.to.a.bp.pdf)

**Comment by deborabonner** [comment]
ACTION NEEDED: Please change the best practice as shown in the attached pdf. 
[Change to a bp.pdf](https://github.com/djaodjin/envconnect/files/2419376/Change.to.a.bp.pdf)


RATIONALE FOR ACTION: In the "Report metrics pop up (edits).pdf" in the above comment box, there is a request to remove the "frequency" [of reporting] option, because the generally accepted best practice is to report externally on an annual basis, so giving the supplier the choice is redundant. The subject of reporting frequency needs to rather be made explicit in the best practice statement itself, rather than the data popup.

**Comment by smirolo** [comment]
Improvements:

(Assessment in Boxes & enclosures > Design > click orange icon next to Product Design).
1. Remove the first comment section.
2. Add a text box before the measures titled "url location of public report".
3. Change Joules to Kilo-Joules and make sure other metrics are in units consistent with the size of the numbers.
4. Redesign the dialog popover (id="report-comments", id="report-measurements-1" and id="report-measurements-2") to be inline expandable accordion.
