### ISSUE TITLE
Send e-mail notification when a supplier has completed its assessment.

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#245]

**Comment by smirolo** [comment]
This was implemented as part of #256.

**Comment by deborabonner** [comment]
This appears not to be working. I completed an Assessment for Testsupplier using industry segment Grounds Maintenance, then clicked Share Scorecard. I got the customised "Share your assessment" email pop up and typed  'Energy Utility (demo)' in the 'share with organization' field. I clicked Send, but never received an email notification about the assessment completion in the email box associated with the 'Energy Utility (demo)' organization.

**Comment by deborabonner** [comment]
<img width="659" alt="screen shot 2018-09-25 at 15 01 42" src="https://user-images.githubusercontent.com/26979575/46019458-fe302280-c0d3-11e8-90b8-23f7c495ab1e.png">
