### ISSUE TITLE
Pop up modifications

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#248]
See mock ups attached.

[TSP - important pop up and text modifications .pdf](https://github.com/djaodjin/envconnect/files/2274709/TSP.-.important.pop.up.and.text.modifications.pdf)

**Comment by deborabonner** [comment]
I signed up as a new user and checked all the pop ups. They look great, but there are a few minor but important edits needed. See attached.
[pop up edits.pdf](https://github.com/djaodjin/envconnect/files/2361472/pop.up.edits.pdf)

**Comment by smirolo** [comment]
Done. Here what the popups look like:
![screen shot 2018-09-11 at 4 03 42 am](https://user-images.githubusercontent.com/3732869/45377051-53394800-b5ae-11e8-8082-8e6388890d57.png)
![screen shot 2018-09-11 at 4 03 53 am](https://user-images.githubusercontent.com/3732869/45377057-56343880-b5ae-11e8-8cac-add8f46307d1.png)
![screen shot 2018-09-11 at 4 04 02 am](https://user-images.githubusercontent.com/3732869/45377064-592f2900-b5ae-11e8-9997-48ad0f4e82fe.png)
![screen shot 2018-09-11 at 4 06 14 am](https://user-images.githubusercontent.com/3732869/45377067-5c2a1980-b5ae-11e8-9cb6-020053308ffe.png)
![screen shot 2018-09-11 at 4 10 43 am](https://user-images.githubusercontent.com/3732869/45377071-5f250a00-b5ae-11e8-8ff9-43fc6055677e.png)
![screen shot 2018-09-11 at 4 17 47 am](https://user-images.githubusercontent.com/3732869/45377074-62b89100-b5ae-11e8-9e9b-4f30257c5b49.png)
![screen shot 2018-09-11 at 4 22 54 am](https://user-images.githubusercontent.com/3732869/45377082-664c1800-b5ae-11e8-8457-eba78fc37436.png)
