### ISSUE TITLE
dashboard: click through on a organization name leads to an error.

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#25]
Investigate what kind of errors.

**Comment by smirolo** [comment]
On performance graphs dashboard (/app/:user/portfolios/totals/):
- click on "boxes-and-enclosures" in top matrix leads to /app/:user/portfolios/boxes-and-enclosures/ (correct)
- click on smaller graph Management basics leads to error message "Cannot derive a metric from this cohort." (correct assuming we don't support top level performance graphs pages for icon-level sections)

On Reporting entities dashboard (/app/info/requests/):

- click on organization the authenticated user has access to leads to a scorecard (correct)
- click on an organization the user just requested access to, i.e. not granted yet, leads to a 403 permission denied (correct).

**Comment by deborabonner** [comment]
An organization with multiple scorecards leads to an "403 permission denied" message.

**Comment by smirolo** [comment]
Note: 403 permission denied because a user is a contributor and only manager and viewer roles are able to access the scorecard.

**Comment by deborabonner** [comment]
Ahaa! Mystery solved. Good stuff!

**Comment by smirolo** [comment]
both contributor and viewer were added to the roles that can access the scorecard. (ref #93).
