### ISSUE TITLE
Make Assessments accessible to supplier managers

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#251]
1) Create access to the online Assessment by inserting the "Learn, Measure, Improve" menus on "supplier manager" views of supplier scorecards.

2) Create "Download Assessment response" option. Next to the "Download scores" button, or in the same spreadsheet, but different tab?

**Comment by smirolo** [comment]
Supplier managers can now also access assessment and planning (read-only).

**Comment by deborabonner** [comment]
Accessibility from the Dashboard-Scorecard route works perfectly.  To be truly useful for TF, it would help if she could see responses from all suppliers on the “Gov & Mgmt – Reporting” practices in the download spreadsheet. Otherwise she has to go into each scorecard one by one to find those responses. Resulting questions: 
--Is it possible to create the ability to download the multiple choice responses from suppliers, or is presentation too complex?
-- If it is possible, should we download all responses, or keep it to just select responses (e.g. at client specific request, like TR) ?
