### ISSUE TITLE
Ghost bps in system

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#264]
See below. For Janitorial Services, I complete all questions visible in the Assessment, but NA shows up in the scorecard. 
<img width="1155" alt="screen shot 2018-09-24 at 13 13 20" src="https://user-images.githubusercontent.com/26979575/45951566-cd7cba00-bffb-11e8-9201-d91a8db59c24.png">

**Comment by smirolo** [comment]
Removed ghost bps:

nb ghosts | industry segment
----------|-------------------
4 | /construction/sustainability-construction/
1 | /lab-services/sustainability-lab-services/
18 | /metal/wire-and-cable/
18 | /metal/distribution-transformers/
1 | /interior-design/sustainability-interior-design/
5 | /facilities/facilities-management-industry/
18 | /metal/general-manufacturing/
2 | /facilities/janitorial-services/
18 | /metal/fabricated-metals/
2 | /architecture-design/sustainability-architecture-design/
1 | /metal/boxes-and-enclosures/
1 | /marketing-and-communications/sustainability-marketing-and-communications/
