### ISSUE TITLE
Scorecard: 2 issues - see below

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#283]
-	Benchmark graph titles are wrapping in on themselves
-	Improvements and reporting data are not showing on the printed scorecard

**Comment by smirolo** [comment]
1/ fixed benchmark graph titles wrapping.
2/ As far as I can tell the improvements and reporting data is showing up. Can you provide a use case?

**Comment by deborabonner** [comment]
2/ See S1 demo for EPC. I continue to find the following: 
--Reporting measures recorded under the "Construction" tile don't show up on screen or the printed version of scorecard.
-- Improvements that are currently highlighted in the "Select for Improvement" column do not show up on screen or the printed version of scorecard.
-- I can't unselect improvements. When I change back to the tile, the improvements have reappeared.
