### ISSUE TITLE
Tile updates (see mockup pdf & graphic below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#291]
![noun_Data_1171433](https://user-images.githubusercontent.com/26979575/62879918-10cf3c80-bd24-11e9-95ea-a91a1ca80b07.png)
[Tile updates.pdf](https://github.com/djaodjin/envconnect/files/3493364/Tile.updates.pdf)

**Comment by smirolo** [comment]
icon uploaded.
