### ISSUE TITLE
Add self-assessment response options to columns and heading rows

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#32]
Those completing the self-assessment may have to select the Not Applicable option for all best practices in an entire best practice list e.g. Energy utility > Electric procurement > Transmission > Materials, or for a section within a list. Being able to select Not Applicable at for an entire list of best practices, or a section therein will significantly facilitate ease of completing the self-assessment for those to whome this will apply.

**Comment by smirolo** [comment]
"Select all" button in the header row. It seemed overkill (and it doesn't look good) to add a "select all" per heading. To be discussed.

**Comment by deborabonner** [comment]
Rather than the green icon button, add a circle button in each heading row. In order to create good visual differentiation with the buttons on the best practice rows, make the buttons on the heading rows larger (or darker or blue?).

**Comment by deborabonner** [comment]
1. Remove green circle from column title cell (e.g. Environmental value).
2. Shrink the green circles to half their current size.
