### ISSUE TITLE
sample.slug missing in API call

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#348]
![Screen Shot 2020-09-18 at 10 34 21 AM](https://user-images.githubusercontent.com/3732869/93636679-33ad3500-f9a9-11ea-814f-64ad830fe11c.png)

**Comment by quiaro** [comment]
Should be fixed with: https://github.com/djaodjin/envconnect/pull/351/commits/caf0c36af506adbfff932d6d2019383401f923ea
