### ISSUE TITLE
Allow multiple active assessments

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#349]
![old-vs-new-app-page](https://user-images.githubusercontent.com/3732869/93638786-c0a5bd80-f9ac-11ea-8568-9488fecca077.png)

In the vue app page, it should be possible to:
1. See more than one assessment in progress (See 'updates' field in `/api/<organization>/benchmark/historical/` API).
2. Create a new assessment unrelated to the ones currently in progress.

**Comment by quiaro** [comment]
My understanding per previous conversations and review of the UI:
- There will only be one active assessment at any given moment. 
- After creating an assessment, the assessment is not tied to any specific industry segment. 
- The user may select an industry segment for the assessment, but it's not until they have answered one question that the industry segment is bound to the assessment.
- It should be possible to change the industry segment of an active assessment (either by resetting the answers in the assessment or by transferring whatever answers there are to the corresponding industry segment). **TBD**

Would you please confirm?

**Comment by smirolo** [comment]
There are multiple active assessments at any given moment and it is possible to create more active assessment.

Now an assessment consists of a `Sample` *and* an industry segment. Currently an industry segment is defined by an industry segment `path`. Since the industry segment is not tied to a `Sample` through the `campaign` field as you would expect, the only way to deduce assessments from the (only) `"is_frozen": false` sample returned by /api/supplier-1/sample/ is to look at the answers and build candidate industry segments.

The easier way is to call the /api/supplier-1/benchmark/history/ API and look at the "updates" field.

**Comment by quiaro** [comment]
I don't see the `updates` field in https://www.tspproject.org/docs/api#RetrieveHistoricalScore. Did you mean the `segments` property?

**Comment by quiaro** [comment]
@smirolo if a user creates an assessment but hasn’t answered any questions, what would the `updates` field look like in the response from https://www.tspproject.org/docs/api/#RetrieveHistoricalScore?

**Comment by smirolo** [comment]
```
Query:http://localhost:8000/envconnect/api/supplier-2/benchmark/historical/
HTTP response:
{
  "results": [],
  "updates": []
}
```

**Comment by smirolo** [comment]
A "continue assessment" button should be inside each assessment card. A button to start on a new industry segment should always be visible.

**Comment by quiaro** [comment]
Would `/api/{organization}/sample/` be deprecated? https://www.tspproject.org/docs/api/#RetrieveHistoricalScore seems to provide the same (plus additional) information.

**Comment by smirolo** [comment]
We still need `/api/{organization}/sample/` to `POST`  (i.e. create) a new assessment.

**Comment by quiaro** [comment]
@smirolo in the results section of the response for https://www.tspproject.org/docs/api/#RetrieveHistoricalScore:
```javascript
"results": [
    {
      "key": "May 2018",
      "created_at": "2018-05-28T17:39:59.368272Z",
      "values": [
        [
          "Construction",
          80,
          "/app/supplier-1/assess/ce6dc2c4cf6b40dbacef91fa3e934eed/sample/boxes-and-enclosures/"
        ]
      ]
    },
    ...
```
1) Will the `values` array only ever have one element? … or when would it be able to have more than one element?
2) What does the number `80` stand for?

**Comment by smirolo** [comment]
Usage example in [envconnect/templates/envconnect/app.html](https://github.com/djaodjin/envconnect/blob/5c3c66df107ce2bc328e1b558d119c56b5af1fd4/envconnect/templates/envconnect/app.html#L76)

**Comment by quiaro** [comment]
If a user has already created and is currently filling in an assessment for the `Construction` industry segment, should `Construction` be removed from the industry list i.e. should the UI prevent users from having more than one active assessment for the same industry segment?

**Comment by smirolo** [comment]
Yes. Or maybe better would to write "Continue" next to the industry item in the dropdown list.
