### ISSUE TITLE
Targets: Integrate benchmarks with API

### ISSUE THREAD

**Issue by quiaro** [djaodjin/envconnect#361]

**Comment by quiaro** [comment]
@smirolo where would I be able to find the `details` and `graph` benchmark endpoints?

**Comment by smirolo** [comment]
[details](https://www.tspproject.org/docs/api/#RetrievePracticeBenchmark) and [graphs](https://www.tspproject.org/docs/api/#RetrieveBenchmark)

**Comment by quiaro** [comment]
@smirolo The wireframes have the following score badge:

<img width="314" alt="Screen Shot 2020-10-07 at 22 59 20" src="https://user-images.githubusercontent.com/311021/95416870-e01b7080-08f0-11eb-8ec7-52259ecb1c61.png">

Even though this is for the scorecard, now that I'm looking at the benchmark data I was wondering where I would get the data for this. Do you know?

**Comment by quiaro** [comment]
@smirolo Looking at the payload from https://www.tspproject.org/docs/api/#RetrieveBenchmark, what are the following for: 
- nb_answers
- nb_questions
- nb_respondents
- numerator
- denominator
- score_weight

Most importantly, how would I be able to get the score coefficient (per the wireframes)?

![Screen Shot 2020-10-08 at 16 52 25](https://user-images.githubusercontent.com/311021/95521439-c0368c00-0986-11eb-9e18-140cea903fe6.png)

**Comment by smirolo** [comment]
The `score_weight` is displayed as the "Total Score Coefficient".

There should be a field called `normalized_score` which is the score displayed. `nb_answers` and `nb_questions` are the total number of answers and questions on that section (or said differently in the subtree). Typically you will not have a `normalized_score` field if `nb_answers < nb_questions`. `numerator` and `denominator` are the numerator and denominator for the score (before it is normalized).
See implementation of [populate_rollup](https://github.com/djaodjin/envconnect/blob/a656f725e00407c3e10c983080e6946f92342a63/envconnect/scores.py#L264) and definition of [Opportunity score](https://www.tspproject.org/docs/faq/#assessment-3)

`nb_respondents` is the number of organizations that have responded to an assessment in that industry segment.

**Comment by quiaro** [comment]
Fixed by https://github.com/djaodjin/envconnect/pull/385
