### ISSUE TITLE
Assessment Nav: Archive an assessment

### ISSUE THREAD

**Issue by quiaro** [djaodjin/envconnect#366]
After an assessment has been frozen, it's no longer possible to delete it. The assessment nav should show an **Archive** button instead.

**Comment by quiaro** [comment]
@smirolo what endpoint should be called for this?

**Comment by smirolo** [comment]
After an assessment has been frozen, it does not show in the active assessments (`updates` field) any more, but will be listed in the [assessment history](https://www.tspproject.org/docs/api/#RetrieveHistoricalScore) (`results` field).
So I would say a frozen assessment is automatically "archived". There is no need for a button.

**Comment by quiaro** [comment]
From the UI perspective, the assumption now is that an assessment will stay active until it is archived. In other words, it will continue to show in the list of active assessments so that it's easier to access/share.

@smirolo If the assessment becomes "archived" the moment it is frozen. Does that mean it should not show anymore in the list of active assessments? ... would it automatically be accessed only from the assessment history? 

Would you be able to confirm since the UI assumes that there **is** a way to distinguish between frozen and archived assessments.

**Comment by smirolo** [comment]
We will remove the archive button. An active assessment is unfrozen while a frozen assessment shows up in the history.
To help in the few cases were an assessment was frozen and the user forgot to share it, or another user for the organization comes along, we will present the latest frozen assessments (less that 6months) on the home/start page.
