### ISSUE TITLE
View assessment history

### ISSUE THREAD

**Issue by quiaro** [djaodjin/envconnect#367]
Show a list of past assessments, their score and a link to their corresponding scorecard.

**Comment by smirolo** [comment]
[historical scores](https://www.tspproject.org/docs/api/#RetrieveHistoricalScore) with an empty path. The history will be in the `results` field.

There should only be a list with links to view the answers/improvement/scorecard as read-only. It doesn't have to be more complicated that the current app for now:

![Screen Shot 2020-10-05 at 9 30 25 AM](https://user-images.githubusercontent.com/3732869/95286850-50ef5980-0819-11eb-8e8d-20a7603363d9.png)

**Comment by quiaro** [comment]
Ok. The answers and the improvement plan would show in the scorecard so it would only seem necessary to have a link to the assessment's scorecard.
