### ISSUE TITLE
Cannot determine assessment from URL

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#388]
![Screen Shot 2020-10-20 at 9 37 53 AM](https://user-images.githubusercontent.com/3732869/96617548-9fd8cc80-12b8-11eb-8058-232ce4138bc6.png)

I recommend that this page's URL be `/app/{organization}/assess/{sample}/{path}/`.
The page at URL `/app/{organization}/assess/{sample}` should redirect directly to `/app/{organization}/assess/{sample}/{path}/` if there is only one segment in the sample, else present options to the user to pick which segment to go to. That's what the [Django implementation does](https://github.com/djaodjin/envconnect/blob/5c3c66df107ce2bc328e1b558d119c56b5af1fd4/envconnect/views/redirects.py#L55).

**Comment by quiaro** [comment]
@smirolo per your comment in https://github.com/djaodjin/envconnect/issues/349, it seems that a sample would always be tied to at least to one industry for the purposes of displaying it in the UI. If it weren't, the response from `updates` would be an empty array and to the UI, this would be the same as not having any active assessments. In other words, the URL `/app/{organization}/assess/{sample}` does not seem practical for UI purposes. It would seem better to have `/app/{organization}/assess/` instead, to denote the path where an assessment is being created and once created the user would be redirected to its corresponding `/app/{organization}/assess/{sample}/{path}/` path.

**Comment by quiaro** [comment]
@smirolo per our meeting:
/app/{organization}/assess/ -create a new assessment
/app/{organization}/assess/{sample}/{path} -assessment landing page
