### ISSUE TITLE
Benchmark graphs: Not duplicating logical sequence from scorecard

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#40]
graphs appear out of order e.g. electric procurement graphs should be grouped, etc

**Comment by smirolo** [comment]
Actually the order is consistent with a depth-first search.

- Electric procurement
    - Materials
        - Transmission
             - Insulators
        - Distribution
             - Boxes & enclosures
             - Breakers
    - Services
    - Power

Will show as:

| | | |
|-|-|-|
 Electric procurement/Materials| Transmission/Insulators |Distribution/Boxes & enclosures
 Distribution/Breakers| Electric procurement/Services |Electric procurement/Power

**Comment by deborabonner** [comment]
Each benchmark graph can have 3 headings: 
1. Always the top level icon heading
2. Followed by any system level heading 
3. Finally, the icon heading below the system level heading
