### ISSUE TITLE
Value summary column headings: change to icons with pop ups.

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#50]
Put current text headings in pop up definitions when one puts cursor on the icon.
This will allow the column width to be shrunk.

**Comment by smirolo** [comment]
relates to #48

**Comment by smirolo** [comment]
After implementing shrinking the text and moving the toolbar icons up to, the columns shrunk enough for the best practice titles to have a natural size. Replacing text by icons would reduce usability of the site as it isn't obvious what icons are standard to represent "Environmental value", "Ops/Maintenance value", etc.

**Comment by deborabonner** [comment]
Logic understood, but icons will look cleaner. I sent them by email.

**Comment by deborabonner** [comment]
Reposition the sort arrow below the icons.
