### ISSUE TITLE
Be able to print a pdf of scorecard and benchmark graphs

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#57]
See attached pdf for mock up. 

[pdf of scorecard.pdf](https://github.com/djaodjin/envconnect/files/1240222/pdf.of.scorecard.pdf)

**Comment by deborabonner** [comment]
- fonts are not loaded properly.
- default icons for benchmark which are not system-level icons are not set properly

**Comment by smirolo** [comment]
Print functionality is working. Opened #138 to track improvements on layout of the page.
