### ISSUE TITLE
Replaces the "system" tag by a "pagebreak" tag

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#58]
Following implementation of #51, the kludge to move between pages of icons through a "system" menu item could be replace by a much better defined `pagebreak` tag.

**Comment by deborabonner** [comment]
See guidance in below image for visual guidance. 
![capture4](https://user-images.githubusercontent.com/26979575/34015428-3ad62482-e0d3-11e7-818b-8ac04c915d7c.PNG)

**Comment by smirolo** [comment]
Implemented and in production for the past 3 weeks. I will close.
