### ISSUE TITLE
"Self assessment" download is incomplete

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#59]

**Comment by deborabonner** [comment]
In excel doc that I downloaded from the "Utility" segment this morning, best practices downloaded from the "Electric Procurement" top level icon, but not from the other three top level icons. Also, the download seems to have pulled from a previous version of the database, because there were two best practices in the download that I deleted yesterday.

**Comment by smirolo** [comment]
Has commit 16be527560 solved the issue?
