### ISSUE TITLE
Update emails sent to Viewers

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#60]
Email text should read as follows: 

You are receiving this email, because you have been added by _____[insert Profile Manager who did the adding]_ as a Viewer on The Sustainability Project (TSP) website for _____[Organization’s name].   You can access the information _____[Organization’s name] by clicking on the previous link, or by cutting and pasting the following link into your browser: _____[insert link]_.

**Comment by deborabonner** [comment]
The "Viewer" email was fixed. Thanks! But I just sent you two emails to indicate minor modifications needed on the "Profile Manager" and "Contributor" email invites too.

**Comment by smirolo** [comment]
latest commit has the final edits.
