### ISSUE TITLE
Djaodjin notification email: change to gender neutral language (if none are outward facing, this isn't a big deal)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#63]
For example, I received an email from support@djaodjin.com titled "A user has activated his account....". There are likely to be as many female users of this system as male, so language should rather be gender neutral. For example, "A user has activated the account....."

**Comment by smirolo** [comment]
This suggestion  was implemented. The title now reads "Account for user ... has been activated on ..."
