### ISSUE TITLE
Promote-demote function not working as should

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#64]
Deb: A heading moved while I was assigning value summary colors. There also wasn't compliance when I tried to drag a heading to promote it. In fact it jumped lower on the list.

**Comment by deborabonner** [comment]
Problem experienced in...

https://tspproject.org/app/info/sustainability-energy-utility/services-e0e656d/

**Comment by smirolo** [comment]
Latests commits: commit 74a9ad7b commit 31fbc10f.
