### ISSUE TITLE
Display in Int Explorer 11: 2 minor items? (see below). 

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#72]
1. "Self-assess > Results > Implementation rate column": Doesn't display green color
2. Toggles for "Results/Self-assessment" and "Value summary/Profitably": text is aligned to top of toggle box, plus the "arrow" design is skew and has an additional color outline on one side (the latter occurs in Chrome too).

**Comment by smirolo** [comment]
Split in 3 as these are separate issues.
