### ISSUE TITLE
Practices sometimes re-order automatically after values are assigned

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#73]

**Comment by smirolo** [comment]
Note from investigation of reported issue: On the browser side, it is confirmed that``sortedOnKeys`` is set by 0 and only switched to 1 when a column sort order is chosen. ``getEntriesAsRows``, thus ``getEntries``, seems to generate a stable order based of the content of the variable ``entries``. It is most likely that the data returned by the server is ordered differently after an update.

To check: stability of SQL request to load ``PageElement`` displayed.
