### ISSUE TITLE
45 degree rotation is not centered around correct pixel

### ISSUE THREAD

**Issue by smirolo** [djaodjin/envconnect#77]
On URL /app/info/sustainability-boxes-and-enclosures/

... or the arrow box is not square.

Taken from #72: Toggle "arrow" design is skew and has an additional color outline on one side (the latter occurs in Chrome too).

**Comment by deborabonner** [comment]
Same issue occurs in MyTSP

**Comment by deborabonner** [comment]
IE 11 issues

**Comment by smirolo** [comment]
Last remaining issue (alignment of text on IE10) fixed with previous commit.
