### ISSUE TITLE
Scorecards not computing correctly (see below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#82]
I completed all questions for 'erinallard' for the "Professional services" segment, but when I click "Score & benchmark" to see the scorecard, it tells me that I haven't completed x number of questions in the self-assessment
![capture2](https://user-images.githubusercontent.com/26979575/27937122-b6c1c9f4-6269-11e7-898f-324556592276.PNG)

**Comment by smirolo** [comment]
confirmed. This is due to ghost questions in the database after a best practice has been deleted. Current workaround is to run `python manage.py clean_up`.

**Comment by deborabonner** [comment]
Great!
