### ISSUE TITLE
Clean up ghost best practicesd so that scorecards can display

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#91]

**Comment by smirolo** [comment]
done.

    $ ../../bin/python manage.py clean_up --delete
    $ ../../bin/python manage.py clean_up --delete
    $ ../../bin/python manage.py clean_up --delete

**Comment by deborabonner** [comment]
Ignore, sorry, just saw your email asking to check #85 as complete. ok will do.  

    On Thursday, August 3, 2017 8:24 AM, Debora Bonner <debora.bonner@att.net> wrote:
 

 Just wanna check, does this take care of #85 too (being able to add and delete best practices without causing more ghosts? 

    On Wednesday, August 2, 2017 11:49 PM, Sebastien Mirolo <notifications@github.com> wrote:
 

 Closed #91.—

**Comment by deborabonner** [comment]
Just wanna check, does this take care of #85 too (being able to add and delete best practices without causing more ghosts? 

    On Wednesday, August 2, 2017 11:49 PM, Sebastien Mirolo <notifications@github.com> wrote:
 

 Closed #91.—
