### ISSUE TITLE
Benchmark graphs are not displaying in scorecards (url eg below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#92]
https://tspproject.org/app/erin-org/benchmark/sustainability-office-space-only/

**Comment by deborabonner** [comment]
Benchmark graphs were not showing up for "Energy efficiency contractor" segement. There may be other segments. 
https://tspproject.org/app/erin-org/benchmark/sustainability-energy-efficiency-contracting/

**Comment by smirolo** [comment]
Issue specific to the energy contracting segment. Correctly opened as #101.
