### ISSUE TITLE
"Viewer" can access all parts of a profile

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#93]
I clicked on the link sent in an email inviting and new "Viewer". It correctly takes one to the Scorecard of the  Organization doing the inviting, but I was able to access the "Self-assessment" and "Improvement planning" too. Viewers are supposed to be restricted to everything by the Scorecard.

**Comment by smirolo** [comment]
Tested with user who is a viewer of S2 -only, as opposed to users which are both viewer and contributor on an organization. The site returns 403 Permission denied as expected for "self-assessment" and "improvement".
