### ISSUE TITLE
Average value column not displaying correct values or any values (see url egs below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#97]
1. The average value column should be gold, but turned white for a couple of bps when I changed the value in one of the cells and then back again.
https://tspproject.org/app/info/sustainability-office-space-only/

2. All values in the average values column are neutral in the "Construction" segment
https://tspproject.org/app/info/sustainability-construction/

and in the "Energy utility (supply chain)" segment. 
https://tspproject.org/app/info/sustainability-energy-utility/services-e0e656d/

**Comment by smirolo** [comment]
1. Average was computed to 5 which is has no color in the legend (green: 0-3, Gold: 6). Fixed by forcing the average to 6 if greater than or equal to 4. i.e. biased average.

2. Fixed incorrect logic to pick hidden columns based on a leading prefix and rerun `migrate_production`.
