### ISSUE TITLE
Total score not displaying on completed self-assessment (see url example below)

### ISSUE THREAD

**Issue by deborabonner** [djaodjin/envconnect#99]
https://tspproject.org/app/erin-org/benchmark/sustainability-office-space-only/

**Comment by smirolo** [comment]
For the record (ref commit 96aaae10):
- "Total score" in the improvement dashboard means total score for the industry segment irrelevant of the section/sub-section being visited.
- "Total score" in the scorecard page means total score for the industry segment.
- "Total score" in MyTSP means total score *across* all industry segments the organization registered as relevant.

Note that test organizations can be in multiple industry segments though the production website will allow an organization to register to exactly *one* industry segment.
